void on_sendFileBtn_clicked();
#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include <ConnectivityManager.h>
#include <ConnectionType.h>
#include <fstream>
#include <mutex>

QT_BEGIN_NAMESPACE
namespace Ui { class MainWindow; }
QT_END_NAMESPACE

/*------------------------------------------------------------------------------------------------------------------
-- HEADER FILE: MainWindow.h - This file contains the class that manages the main application window.
--
-- PROGRAM: Knekt
--
-- FUNCTIONS:
-- static DWORD WINAPI UIThread(void* param)
-- static DWORD WINAPI SendThread(void* param)
-- Connection* getConnection() const
--
-- DATE: Feb 12, 2020
--
-- REVISIONS: N/A
--
-- DESIGNER: Henry Ho
--
-- PROGRAMMER: Henry Ho
--
-- NOTES:
-- This class template was auto-generated by Qt upon creating this project.
------------------------------------------------------------------------------------------------------------------*/
static std::mutex mtx;

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    MainWindow(QWidget *parent = nullptr);
    ~MainWindow();
    static DWORD WINAPI UIThread(void* param);
    static DWORD WINAPI SendThread(void* param);

    /*------------------------------------------------------------------------------------------------------------------
    -- FUNCTION: getConnection(void)
    --
    -- DATE: Feb 12, 2020
    --
    -- REVISIONS: N/A
    --
    -- DESIGNER: Henry Ho
    --
    -- PROGRAMMER: Henry Ho
    --
    -- INTERFACE: Connection* getConnection(void) const
    --
    -- RETURNS: Connection*
    --
    -- NOTES:
    -- Use this function to get the current active connection
    ------------------------------------------------------------------------------------------------------------------*/
    Connection* getConnection() const {
        return currConnection;
    }

    void setSentData(unsigned long bytesSent, unsigned int packets);
    void setReceivedData(unsigned long bytesReceived, unsigned int packets);
    void setTimeElapsedOutput(int);

    int getPacketSize();
    int getNumberOfTimesToSend();

private slots:
    void on_actionTCP_triggered();
    void on_actionUDP_triggered();

    void on_actionClient_triggered();
    void on_actionServer_triggered();

    void on_connectBtn_clicked();

    void on_sendPacketBtn_clicked();

    void on_sendFileBtn_clicked();

    void on_receiveBtn_clicked();

private:
    Ui::MainWindow *ui;
    ConnectionType connectionType;
    ProtocolType protocolType;
    Connection* currConnection;
    bool isConnected = false;
    bool isReceiving = false;
    HANDLE SendThreadHandle;
    DWORD SendThreadId;
    HANDLE UIThreadHandle;
    DWORD UIThreadId;
};

#endif // MAINWINDOW_H
